# Generated by Django 5.2.5 on 2025-09-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDoctorMap',
            new_name='PatientDoctorMapping',
        ),
        migrations.RenameIndex(
            model_name='patientdoctormapping',
            new_name='clinic_pati_patient_abf339_idx',
            old_name='clinic_pati_patient_569e9b_idx',
        ),
    ]
